apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-nodejs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backend-nodejs.name" . }}
    helm.sh/chart: {{ include "backend-nodejs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backend-nodejs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "backend-nodejs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.configmapGcloudService }}
      volumes:
        - name: gcloudservice
          configMap: {{ .Values.configmapGcloudService }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.configmapGcloudService }}
          volumeMounts:
            - name: gcloudservice
              mountPath: "/etc/GOOGLE_APPLICATION_CREDENTIALS"
              readOnly: true
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ .Values.env.googleApplicationCredentials }} 
            - name: EVENT_STORE_BROKER_TYPE
              value: {{ .Values.env.eventStoreBrokerType }}
            - name: EVENT_STORE_BROKER_EVENTS_TOPIC
              value: {{ .Values.env.eventStoreBrokerEventsTopic }}
            - name: EVENT_STORE_STORE_TYPE
              value: {{ .Values.env.eventStoreType }}
            - name: EVENT_STORE_STORE_URL
            {{- if .Values.env.secretEventStoreURL }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretEventStoreURL }}
                  key: {{ .Values.env.secretEventStoreURLKey }}
            {{- else }}
              value: {{ .Values.env.eventStoreURL }}
            {{- end }}
            - name: EVENT_STORE_STORE_AGGREGATES_DB_NAME
              value: {{ .Values.env.eventStoreAggregatesDB }}
            - name: EVENT_STORE_STORE_EVENTSTORE_DB_NAME
              value: {{ .Values.env.eventStoreNameDB }}
            - name: MONGODB_URL
            {{- if .Values.env.secretMongodbUrl }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretMongodbUrl }}
                  key: {{ .Values.env.secretMongodbUrlKey }}
            {{- else }}
              value: {{ .Values.env.mongodbUrl }}
            {{- end }}
            - name: MONGODB_DB_NAME
              value: {{ .Values.env.mongodbNameDB }}
            - name: JWT_PUBLIC_KEY
            {{- if .Values.env.secretJwtPublicKey }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configmapJwtPublicKey }}
                  key: {{ .Values.env.configmapKeyJwtPublicKey }}
            {{- else }}
              value: {{ .Values.env.jwtPublicKey }}
            {{- end }}
            - name: EMI-GATEWAY_REPLIES_TOPIC_SUBSCRIPTION
              value: {{ .Values.env.emiGatewayRepliesTopicSubscription }}
            - name: REPLY_TIMEOUT
              value: {{ .Values.env.replyTimeout | quote }}
            - name: BROKER_TYPE
              value: {{ .Values.env.brokerType }}
            - name: LOCKVERSION
              value: {{ .Values.env.lockVersion | quote }}
            {{- if .Values.env.keycloak.enabled }}
            - name: KEYCLOAK_BACKEND_BASE_URL
            {{- if .Values.env.keycloak.configmapBaseURL }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.keycloak.configmapBaseURL }}
                  key: {{ .Values.env.keycloak.configmapBaseURLKey }}
            {{- else }}
              value: {{ .Values.env.keycloak.baseURL }}
            {{- end }}
            - name: KEYCLOAK_BACKEND_USER
            {{- if .Values.env.keycloak.secretUser }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.keycloak.secretUser }}
                  key: {{ .Values.env.keycloak.secretUserKey }}
            {{- else }}
              value: {{ .Values.env.keycloak.user }}
            {{- end }}
            - name: KEYCLOAK_BACKEND_PASSWORD
            {{- if .Values.env.keycloak.secretPassword }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.keycloak.secretPassword }}
                  key: {{ .Values.env.keycloak.secretPasswordKey }}
            {{- else }}
              value: {{ .Values.env.keycloak.password }}
            {{- end }}
            - name: KEYCLOAK_BACKEND_CLIENT_ID
              value: {{ .Values.env.keycloak.clientId }}
            - name: KEYCLOAK_BACKEND_REALM_NAME
              value: {{ .Values.env.keycloak.realmName }}
            {{- end }}
{{- with .Values.extraEnv }}
{{ tpl . $ | indent 12 }}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
